### ISSUE TITLE
Context Menu Support

### ISSUE THREAD

**Issue by donCarlosOne** [Mintonne/add-to-globals#1]
I've modified your package.json file to include context menu support for adding/removing global variables.  Makes it much easier to use.  Here's the relevant JSON you can add after "commands" in the "contributes" section in package.json.  You'll want to update your little screen demo before releasing this:

"menus": {
			"editor/context": [
				{
					"command": "atg.true",
					"when": "editorLangId == javascript && editorHasSelection",
					"group": "1_Globals@1"
				},
				{
					"command": "atg.false",
					"when": "editorLangId == javascript && editorHasSelection",
					"group": "1_Globals@2"
				},
				{
					"command": "atg.remove",
					"when": "editorLangId == javascript && editorHasSelection",
					"group": "1_Globals@3"
				}
			]
		}

![image](https://user-images.githubusercontent.com/2841617/58234240-66f09d00-7d3e-11e9-99db-e205611e71ba.png)

**Comment by Mintonne** [comment]
Hey,

Would it be possible to disable them? I tried to skim read the vscode docs but couldn't find anything.

Adding variables to globals isn't needed that often and I would prefer not to bloat the context menu.
